// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ArticleComment struct {
	ID         int64              `json:"id"`
	ArticleID  int64              `json:"article_id"`
	UserID     int64              `json:"user_id"`
	AuthorName pgtype.Text        `json:"author_name"`
	Content    pgtype.Text        `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ArticleLike struct {
	ID        int64              `json:"id"`
	ArticleID int64              `json:"article_id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             int64              `json:"id"`
	IdentifierHash string             `json:"identifier_hash"`
	DisplayName    pgtype.Text        `json:"display_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
