// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserByIdentifierHash(ctx context.Context, identifierHash string) (int64, error)
}

var _ Querier = (*Queries)(nil)
